### ISSUE TITLE
Intellibot does not support new FOR syntax

### ISSUE THREAD

**Issue by zastress** [lte2000/intellibot#3]
Starting with RF 3.1 there is a new syntax for `FOR` loops.
Old Implementation:
```
:FOR    ${animal}    IN    cat    dog    cow
\    Keyword    ${animal}
\    Another keyword
```

New implementation:
```
FOR    ${animal}    IN    cat    dog    cow
    Keyword    ${animal}
    Another keyword
END
```

More details here: https://github.com/robotframework/robotframework/blob/master/doc/releasenotes/rf-3.1.rst#for-loop-enhancements

**Comment by lte2000** [comment]
Neither new loop syntax nor old for loop is supported by original Intellibot.
You don't see red underline with old : FOR just because it skip inspection explicitly.

I do some quick dev, now it should resolve keyword and variable in the loop correctly (you can see different font used comapring with old plugin). Please try the attached intellibot.jar
[intellibot.zip](https://github.com/lte2000/intellibot/files/3858579/intellibot.zip)

It also support resolve variables using extended syntax, e.g, ${var * 10 + 3}

**Comment by zastress** [comment]
Installed the plugin in the archive. It seems it only recognizes de `END` section. See printscreen
![2019-11-18_1437](https://user-images.githubusercontent.com/37159441/69053010-1fa74880-0a11-11ea-9475-859239c013f2.png)

**Comment by lte2000** [comment]
updated:
[intellibot.zip](https://github.com/lte2000/intellibot/files/3858687/intellibot.zip)

**Comment by zastress** [comment]
It's ok now.

**Comment by lte2000** [comment]
code in dev_0.10.143.386.
Please download and install the intellibot.jar from https://github.com/lte2000/intellibot
